/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TravelEntry = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'distanceKm' : IDL.Float64,
  'departure' : IDL.Text,
});
export const Preset = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'name' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'departure' : IDL.Text,
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addPreset' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'deletePreset' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(TravelEntry)], ['query']),
  'getAllPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TravelEntry = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'distanceKm' : IDL.Float64,
    'departure' : IDL.Text,
  });
  const Preset = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'name' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'departure' : IDL.Text,
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addPreset' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'deletePreset' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(TravelEntry)], ['query']),
    'getAllPresets' : IDL.Func([], [IDL.Vec(Preset)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };