/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Preset {
  'id' : bigint,
  'destination' : string,
  'name' : string,
  'distanceKm' : number,
  'departure' : string,
}
export interface TravelEntry {
  'id' : bigint,
  'destination' : string,
  'date' : string,
  'note' : [] | [string],
  'createdAt' : bigint,
  'distanceKm' : number,
  'departure' : string,
}
export interface _SERVICE {
  'addEntry' : ActorMethod<
    [string, string, string, number, [] | [string]],
    bigint
  >,
  'addPreset' : ActorMethod<[string, string, string, number], bigint>,
  'deleteEntry' : ActorMethod<[bigint], undefined>,
  'deletePreset' : ActorMethod<[bigint], undefined>,
  'getAllEntries' : ActorMethod<[], Array<TravelEntry>>,
  'getAllPresets' : ActorMethod<[], Array<Preset>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];